# Generated by Django 2.0 on 2019-07-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
