# Generated by Django 2.0 on 2019-07-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190723_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
